### ISSUE TITLE
Error In handle_eval, 这是怎么回事，另外你的训练代码有分享的计划吗？

### ISSUE THREAD

**Issue by liutianling** [nju-websoft/DSKG#1]
MemoryError                               Traceback (most recent call last)
<ipython-input-13-4dababce2921> in <module>()
      2 for i in range(epoch, max_epoch):
      3     if i % 20 == 0:
----> 4         handle_eval(i=i, last_mean_loss=last_mean_loss, valid=True, test=False)
      5     last_mean_loss = model.train()
      6     epoch += 1

<ipython-input-10-bc8b4fbf2ad6> in handle_eval(i, last_mean_loss, valid, test)
     49 def handle_eval(i=0, last_mean_loss=1000, valid=True, test=False):
     50     if valid:
---> 51         jfr, efr = joint_eval(test_data=valid_data, filter_mat=vfilter_mat, rev_rel=vrev_rel)
     52         jrr, rr = joint_eval_raw(test_data=valid_data, filter_mat=vfilter_mat, rev_rel=vrev_rel)
     53 

<ipython-input-10-bc8b4fbf2ad6> in joint_eval(test_data, filter_mat, rev_rel)
     12 
     13     ep =  eval_entity_prediction(model, data=test_data, filter_mat=filter_mat, return_probs=True)
---> 14     efr = cal_r(ep, label, filter_mat)
     15     if use_jeval:
     16         rp = eval_relation_prediction(model, rev_rel_test_data, filter_mat=None, return_probs=True).T

<ipython-input-10-bc8b4fbf2ad6> in cal_r(probs, label, filter_mat)
      1 def cal_r(probs, label, filter_mat):
----> 2     filter_probs = probs * filter_mat
      3 
      4     filter_probs[range(len(label)), label] = probs[range(len(label)), label]
      5     filter_ranks = cal_ranks(filter_probs, method='min', label=label)

MemoryError:

**Comment by guolingbing** [comment]
To improve the speed of evaluation, we actually save a very large matrix in the memory. 
So, we suggest using a computer with 64GB+ memory to run it, or rewrite the evaluation function.
